<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="_Default" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Home | My Travel Ireland</title>  
    <link href="css/slicebox.css" rel="stylesheet" type="text/css" />   
    <link href="css/animate.min.css" rel="stylesheet" type="text/css" />
    <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="css/main.css" rel="stylesheet" type="text/css" />    
    <link href="css/responsive.css" rel="stylesheet" type="text/css" />
    <link href="css/font-awesome.css" rel="stylesheet" type="text/css" />  
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css"        rel="stylesheet" type="text/css" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->


</head>
<body>
    <form id="form1" runat="server">
   <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNav">
                    <span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar">
                    </span>
                </button>
                <a href="#" class="navbar-brand">
                    <img src="images/logo.jpg" />
                </a>
            </div>
            <div id="myNav" class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="active"><a href="#">Home</a></li>
                   <!-- <li><a href="#">MyTravel</a></li> -->
                   <!-- <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">My Favorites
                        <span class="caret"></span></a>
                         <ul class="dropdown-menu">
                            <li><a href="#">Irish Counties</a></li>
                            <li><a href="#">Best Waterfalls in Ireland</a></li>
                            <li><a href="#">Top Irish Villages</a></li>
                            <li><a href="#">Activities in Ireland</a></li>
                           <!-- <li class="divider"></li> -->
                          <!--  <li><a href="#">Lakes around Dublin</a></li>
                        </ul>
                    </li> -->
                    <li><a href="">Mohammed Bukhamsin</a></li>
                      <!--<li><a href="#">Contact me</a></li> -->
                </ul>
            </div>
        </div>
    </div>
    <br />
    <div class="border">
    </div>
    <!-- Start cssSlider.com -->
    <!-- Generated by cssSlider.com 1.9 -->
    <link rel="stylesheet" href="slider/csss_engine1/style.css">
    <!--[if IE]><link rel="stylesheet" href="slider/csss_engine1/ie.css"><![endif]-->
    <!--[if lte IE 9]><script type="text/javascript" src="slider/csss_engine1/ie.js"></script><![endif]-->
    <script type="text/javascript" src="slider/csss_engine1/gestures.js"></script>
    <div class='csslider1 autoplay '>
        <input name="cs_anchor1" id='cs_slide1_0' type="radio" class='cs_anchor slide'>
        <input name="cs_anchor1" id='cs_slide1_1' type="radio" class='cs_anchor slide'>
        <input name="cs_anchor1" id='cs_slide1_2' type="radio" class='cs_anchor slide'>
        <input name="cs_anchor1" id='cs_slide1_3' type="radio" class='cs_anchor slide'>
        <input name="cs_anchor1" id='cs_play1' type="radio" class='cs_anchor' checked>
        <input name="cs_anchor1" id='cs_pause1_0' type="radio" class='cs_anchor pause'>
        <input name="cs_anchor1" id='cs_pause1_1' type="radio" class='cs_anchor pause'>
        <input name="cs_anchor1" id='cs_pause1_2' type="radio" class='cs_anchor pause'>
        <input name="cs_anchor1" id='cs_pause1_3' type="radio" class='cs_anchor pause'>
        <ul>
            <li class="cs_skeleton">
                <img src="slider/csss_images1/1.jpg"
                    style="width: 100%;"></li>
            <li class='num0 img slide'>
                <img src='slider/csss_images1/AdareCountyLimerick1.jpg'
                    alt='abstract-desktop-wallpaper-widescreen-top-model-computers-wallpapers-wallwuzz-hd-wallpaper-10823'
                    title='abstract-desktop-wallpaper-widescreen-top-model-computers-wallpapers-wallwuzz-hd-wallpaper-10823' /></li>
            <li class='num1 img slide'>
                <img src='slider/csss_images1/KinsaleCountyCork.png' alt='aura_rays_hd_1080p-HD'
                    title='aura_rays_hd_1080p-HD' /></li>
            <li class='num2 img slide'>
                <img src='slider/csss_images1/DingleCountyKerry1.jpg' alt='qxt1j-wallpapers-515728052-1920x1080'
                    title='qxt1j-wallpapers-515728052-1920x1080' /></li>
            <li class='num3 img slide'>
                <img src='slider/csss_images1/DingleCountyKerry2.jpg' alt='wpid-Abstract-Colorful-Wallpaper-Hd-0'
                    title='wpid-Abstract-Colorful-Wallpaper-Hd-0' /></li>
        </ul>
        <div class='cs_play_pause'>
           <%-- <label class='cs_play' for='cs_play1'>
                <span><i></i><b></b></span>
            </label>--%>
            <label class='cs_pause num0' for='cs_pause1_0'>
                <span><i></i><b></b></span>
            </label>
            <label class='cs_pause num1' for='cs_pause1_1'>
                <span><i></i><b></b></span>
            </label>
            <label class='cs_pause num2' for='cs_pause1_2'>
                <span><i></i><b></b></span>
            </label>
            <label class='cs_pause num3' for='cs_pause1_3'>
                <span><i></i><b></b></span>
            </label>
        </div>
    
    </div>
    <!-- End cssSlider.com -->
    <div class="container">
        <h1>
            Dublin
        </h1>
        <div class="border">
        </div>
        <div class="row">
            <p>
                <a class="ribbon date " title="12th March 2015">
                    <div class="top ribbon-piece">Mar 12</div>                                  
                </a>
               <h3>Things to Do  </h3> 
            </p>
            <div class="separator" style="clear: both; text-align: center;">
                <a href="images/huhuDuplin.png"  style="margin-left: 1em; margin-right: 1em;">
                    <img border="0" height="202" width="320" src="images/huhuDuplin.png" class="" style="display: inline-block;"> </img>
                </a>
            </div>
            <div class="entry-content" style="-webkit-text-stroke-width: 0px; background-color: white; border: 0px; color: #444444; font-family: 'Open Sans', Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 1.714285714; margin: 0px; orphans: auto; padding: 0px; text-align: start; text-indent: 0px; text-transform: none; vertical-align: baseline; white-space: normal; widows: auto; word-spacing: 0px;">
                <div style="border: 0px; font-size: 14px; line-height: 1.714285714; margin: 0px 0px 1.714285714rem; padding: 0px; vertical-align: baseline;">
                    Just on the right of the main gate when you enter the park, you will see a fenced room. Here you can rent a bicycle and go see the deers and rabbits in the park. Just be careful from the bull dog this guy has.</div>
            
                <div style="border: 0px; font-size: 14px; line-height: 1.714285714; margin: 0px 0px 1.714285714rem; padding: 0px; vertical-align: baseline;">
                    2- Open Market in Dublin are lovely especially for Families, Sunday market in Dun-Laoghaire in the people park, Wednesday market in Stillorgan.</div>
            
                <div style="border: 0px; font-size: 14px; line-height: 1.714285714; margin: 0px 0px 1.714285714rem; padding: 0px; vertical-align: baseline;">
                    3- Book of Kells, well don’t say I did not worn you. Although this place is one of the treasures of Dublin and Moreover, one of the best ten Libraries in the world, This place is not for people that do not like Historical places or books because it is not free.<br>
            
                <div class="separator" style="clear: both; text-align: center;">
                    <a href="images/Duplin2.png" style="margin-left: 1em; margin-right: 1em;">
                    <img border="0" height="253" width="320" src="http://4.bp.blogspot.com/-mPjoNcVHxp4/VQRTxs8eYpI/AAAAAAAAAVA/6jgWjJn_g2U/s1600/tr.png" class="" style="display: inline-block;"></a>
               </div>
            </div>
        </div>

    </div>    
    <section id="section-bar">
    </section>

     <div class="container">
        <h1>
            26 +6 Irish Counties
        </h1>
           <a class="ribbon date " title="25th Feb 2015" href="" itemprop="url">
                <div class="top ribbon-piece">Feb 25</div>                                  
           </a>
        <div class="border">
        </div>
        <div class="row">
            <p>
               Here I will show a picture of each county according to my journey, my aim is to have a record of 26 counties and two or three from the Northerner Ireland (Ulster). Up to date I have finished from visiting 20 counties.
                Lets start with the less famous counties, This is like a summery of my three year journy to Ireland. Up to now all the pictures below are mine except for county Monagan. I still did post a picture of County louth. Despite the fact that I have visited county louth many times.
            </p>
            <p>
                1- County Sligo

            </p>
            <p>
                I still did not visit county Sligo but I am eager to pay a good visit to Sligo. For a starter I will show
                you the city and the famous mountain . I seriously need to get one quadricopter (drone camera), it is the only way to have a full view
                of the beauty of Irish landscape.
            </p>
            <p>
                2- County Cavan
            </p>
            <p> </p>         
            <p>
                3- County Monagan
            </p>
                <h3 style="-webkit-text-stroke-width: 0px; color: #333333; font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px;"> </h3>
            <p>
                I have only visited Carrickmacross but I plan to visit the Castle Leslie to do some horse riding.
            </p>
            <div class="separator" style="clear: both; text-align: center;">
            <a href="" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" height="240" width="320" src="http://4.bp.blogspot.com/-AYlia0FIPnA/VWXw01hm4ZI/AAAAAAAAAWo/jfm-M1apEW4/s320/equestrian-6.jpg" class="" style="display: inline-block;"></a>

            </div>
            <p>
                4- County Louth
            </p>
                 <h3 style="-webkit-text-stroke-width: 0px; color: #333333; font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px;"> </h3>

            <p>
                5- County Meath
            </p>
                 <h3 style="-webkit-text-stroke-width: 0px; color: #333333; font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px;"> </h3>
            <p>
                6- County Clare
            </p>
             <p>
                This picture was taken on my way from Ballyvaughan to Cliffs of Moeher.
            </p>
                 <h3 style="-webkit-text-stroke-width: 0px; color: #333333; font-family: Georgia, 'Times New Roman', 'Bitstream Charter', Times, serif; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px;"> </h3>
            <p>
                7-County Dublin
            </p>

        </div>

    </div>

    <section id="section-bar">
      <!-- <div class="container">
      </div> -->
     </section>

        <div class="container">
        <h1>
            Best Waterfalls in Ireland
        </h1>
        <div class="border">
        </div>
        <div class="row">
            <p>
                 1- Essaranka Waterfall            
            </p>
            <p>
                At last I got the chance to pay a visit to the north counties of Ireland. It was an amazing moment driving through the Glengesh pass in county Donegal, near Ardara. The waterfall is also a miles away from Ardara. The driver was talking about the people living down here that had to leave to America in the 1800 and the transition of moving from a valley to New York City.
            </p>
            <p>
               2- Glencar Waterfall
            </p>
            <p>
               Located 8 miles northern Sligo Town, the romantic looking waterfall is 50 ft high. This is neither the largest nor allest waterfall in the country but it is by far the most beautiful one. I could not take my eyes off it. Simply stunning view. Just do not be fooled by the wind funnel at the entrance, the wind is is just ok inside.
            </p>
            <p> </p>         
            <p>
                3-Mohan Waterfall
            </p>
            <p>
                Located in County Waterford, as per my personal Experience, it is the largest Waterfall in the country.
                I discovered it when i was driving to Cork, I saw a sign saying Mohan waterfalls, I thought it must be a tiny one since I have never heard about it. To my surprise, it was huge. It was a nice adventure to clibm up to the top.            </p>
            <p></p>
            <p>
               4- Torc Waterfalls
            </p>
            <p></p>
            <p>
                Located in County Waterford, as per my personal Experience, it is the largest Waterfall in the country.I discovered it when i was driving to Cork, I saw a sign saying Mohan waterfalls, I thought it must be a tiny one since I have never heard about it. To my surprise, it was huge. It was a nice adventure to clibm up to the top.
            </p>
            <p></p>
            <p>
               5- Powerscourt Waterfalls
            </p>
            <p>
               Very close to Dublin, its 20 minute drive from Dublin. This is the tallest waterfall in Ireland, with a nice surrounding place suitable for families, its 4 kilometers from Powerscourt Gardens in Enniskerry, county Wicklow. The Garden can be reached by bus but for the falls you have to go by a car. Last time we had a nice walk along the river that starts from the waterfall. 
            </p>
            <p></p>
            <p>
                6- Gleninchaquin Waterfall
            </p>
            <p>
                In the Gleninchaquin Park, This valley provides a stunning view. It is perfect for a day out,
                other activities such as fishing.
            </p>
            <p></p>
            <p>

            </p>
        </div>

    </div>
    
     <section id="section-bar">
      <!-- <div class="container">
      </div> -->
     </section>
         <div class="container">
        <h1>
            Top Irish Villages
        </h1>
        <div class="border">
        </div>
        <div class="row">
            <p>
               1-Adare           
            </p>
            <p>
                I was traveling with two more cars back to Dublin from Killarney in county Kerry but on our war suddenly every one was looking from the right window and making wow sounds when we passed by the well kept cottages in Adare and the icing on the cake Manor castle, a spectacular castle by river Maigue, only later I discovered that this old castle is a five start hotel which explained seeing many people dressed as if they were attending a wedding.    </p>
            <p>
              2-Carlingford
            </p>
            <p>
               This small Town is in the northern part of the republic of Ireland in Cooley peninsula. Actually I had no idea that the town was fabulous but rather I went there to the adventure center to play zorbing (for info and picture about zorbing see the activity article) only then I discovered the village. The best part of the trip apart from the activities was the coastal drive along lough carlingford, it was a memorable drive that I wish to do again.
            </p>
            <p> </p>         
            <p>
               3-Kinsale
            </p>
            <p>
               I visited County Cork three times and every time I end up visiting Belarney Castle but never went to Kinsale or Cobh but next time when head south I effeminately will pay a visit.            <p></p>
            <p>
             4-Slane
            </p>
            <p></p>
            <p>
                By and large this is the smallest village I ever encountered in my life, what amazed me more is that despite the little number of houses the village had two art studios or shops.But after seeing the terrific scenery no wonder they had two art shops. Visiting Slane was part of the boyne valley trip where we first visited the Newgrange and Trim Castle and of course the hill of Slane. If you are a fan of nature and greenery.            </p>
            <p></p>
            <p>
              5- Dalkey
            </p>
            <p>
               This is one of my favorite places in Dublin such a class village with delicate coffee shops and restaurants. One could spend more than a day to cover the main attractions over there. the castle in the background of the picture above is nice because you get to have a tour with people dressing and speaking like the old English solders who used be in the castle. Then there days we take the kids to Killiney hill park, the kids enjoy playing while we get a nice top view of the sea. Finaly there are cliffs like Hawk Cliff and killiney beach. Not to forget mentioning the famous Vico road one of the best roads for cycling.            </p>
            <p></p>
            <p>
               6- Killaloe
            </p>
            <p>
                I was in Ballina county Tipperary while taking this picture, the other side of the river is Killaloe county Clare. The cruise trip was amazing I guess the scenery that could be seen on the boat is something that you rarely can see in other places with lots of nice cottages on both sides of the river.
            </p>
            <p></p>
            <p>
                7- Dingle
            </p>
                <p>
                    Dingle town is in the Dingle Peninsula in the east coast of Ireland. This is a perfect place to escape from the city to rural Ireland where its normal to see cattle blocking the road. There are about nine beaches along the coast.
                </p>
                <p></p>
                <p>
                    8-Ardara
                </p>
                <p></p>
                <p>
                    9-Lismore
                </p>
                <p>
                    I visited this castle in 2012 not knowing that it is not opened for tourist except for the garden. Really, this whole castle is for rent!! Amazing. The castle was Built in 1185 by King John according to their brochure. Seeing the castle great but what was astonishing for me was this little village, you really have the feeling of an untouched village in the 19th century. I had to visit the place again but not for seeing the castle again but to collect my wife's Iphone that she has forgotten in the castle. Therefore I had to drive from Killarney.
                </p>
                <p>
                </p>
        </div>

    </div>
    <section id="section-bar">
      <!-- <div class="container">
      </div> -->
     </section>
         <div class="container">
        <h1>
            Activities in Ireland
        </h1>
        <div class="border">
        </div>
        <div class="row">
            <p>
               I came to Ireland to do Masters my self and my wife. This is now my third year and unlike others I feel its just the start. I have too many plans and places to go to. Most of the pictures are mine but some are from the internet but worry not I will replace them once I dig in my hard disc or in other cases once I visit or revisit that place. 

                Here below I shall list my Favourite activities  in Ireland.

            <p> My top five are:   </p>     
            </p>
            <p>
               1- Zorbing
            </p>
            <p>
               This picture above was taken last winter in Carlingford adventare centre.
            </p>
            <p> </p>         
            <p>
                2-Horse Riding
            </p>
            <p>
            The horse above was seen enjoying the waters in Dublin west, specifically in Clondalkin. 
            </p>
            <p>
            3-Archery
            </p>
            <p>One of the many activities available in the hotel in Blessington was Archery.</p>
            <p>
                By and large this is the smallest village I ever encountered in my life, what amazed me more is that despite the little number of houses the village had two art studios or shops.But after seeing the terrific scenery no wonder they had two art shops. Visiting Slane was part of the boyne valley trip where we first visited the Newgrange and Trim Castle and of course the hill of Slane. If you are a fan of nature and greenery.            </p>
            <p></p>

            <p>
              4- Kayaking
            </p>
            <p>
              Getting use of the liffey River. The river view gets better the more you head east towards the see as it becomes deeper and wider which makes it look clean and clearly blue. Moreover, the Sameul Becket (musical) bridge along with the leaning conventional center form a magical view especially at night.
                <p></p>
            <p>
              5-Skydiving in the Midlands
            </p>
            <p>
                I was in Ballina county Tipperary while taking this picture, the other side of the river is Killaloe county Clare. The cruise trip was amazing I guess the scenery that could be seen on the boat is something that you rarely can see in other places with lots of nice cottages on both sides of the river.
            </p>
            <p></p>
            <p>
                7- Dingle
            </p>
                <p>
                    Dingle town is in the Dingle Peninsula in the east coast of Ireland. This is a perfect place to escape from the city to rural Ireland where its normal to see cattle blocking the road. There are about nine beaches along the coast.
                </p>
                <p></p>
                <p>
                    8-Ardara
                </p>
                <p></p>
                <p>
                    9-Lismore
                </p>
                <p>
                    I visited this castle in 2012 not knowing that it is not opened for tourist except for the garden. Really, this whole castle is for rent!! Amazing. The castle was Built in 1185 by King John according to their brochure. Seeing the castle great but what was astonishing for me was this little village, you really have the feeling of an untouched village in the 19th century. I had to visit the place again but not for seeing the castle again but to collect my wife's Iphone that she has forgotten in the castle. Therefore I had to drive from Killarney.
                </p>
                <p>
                </p>
        </div>
    </div>
      <section id="section-bar">     </section>
  
     <div class="container">
        <div class="row">

    </div>
    <div class="container-fluid" id="infoSection">
    <div class="col-md-3" >
      <h6 key="callus" >All rights reserved 2017@      
        <i class="fa fa-map-marker" aria-hidden="true"></i> <span key="address" align ="Center"> www.five-tech.com </span>
        <br>
        <i class="fa fa-phone" aria-hidden="true"></i> +966-537-609-448
        <br>
        <i class="fa fa-envelope" aria-hidden="true"></i> marketing@five-tech.com
      </p>
        <a href="#" class="back-to-top"><i class="fa fa-2x fa-angle-up"></i></a>
        </h6>
    </div>
    <!--/#footer-->
    <!-- Back To Top -->
    <script type="text/javascript">
        jQuery(document).ready(function () {
            var offset = 300;
            var duration = 500;
            jQuery(window).scroll(function () {
                if (jQuery(this).scrollTop() > offset) {
                    jQuery('.back-to-top').fadeIn(duration);
                } else {
                    jQuery('.back-to-top').fadeOut(duration);
                }
            });

            jQuery('.back-to-top').click(function (event) {
                event.preventDefault();
                jQuery('html, body').animate({ scrollTop: 0 }, duration);
                return false;
            })
        });
    </script>
    <!-- /top-link-block -->
    <!-- Jscript -->
    <script src="js/jquery.js" type="text/javascript"></script>
    <script src="js/bootstrap.min.js" type="text/javascript"></script>   
    <script src="js/main.js" type="text/javascript"></script>
    <script src="js/wow.min.js" type="text/javascript"></script>

    </form>
</body>
</html>
